name: VanishNoPickup
main: com.nilla.vanishnopickup.VanishNoPickup
version: 1.7
author: EvilNilla
commands:
  vanish:
    description: Toggles your visibility
    aliases: poof
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players
  nopickup:
    description: Toggles Picking Up Items
    aliases: np
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles Your Ability to Pickup Items
           /<command> list - List of players with Item Pickup Disabled