name: VanishNoPickup
main: com.nilla.vanishnopickup.VanishNoPickup
version: 1.9.12+essentials2
author: EvilNilla
softdepend: [Permissions,Essentials]
commands:
  vanish:
    description: Toggles your visibility
    aliases: poof
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles your visibility
           /<command> list - List of invisible players
           /<command> reload - Reloads the config
           /<command> hide [player] - Hides a player from lists and joining/quit
           /<command> unhide [player] - Disables the hiding
           /<command> aggro - Toggles if mobs should aggro the player
  nopickup:
    description: Toggles Picking Up Items
    aliases: np
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Toggles Your Ability to Pickup Items
           /<command> list - List of players with Item Pickup Disabled
  fakequit:
    description: Fakes your leaving of the server
    aliases: fq
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Fakes your leaving of the server
  fakejoin:
    description: Fakes your joining of the server
    aliases: fj
    usage: |
           Incorrect usage of /<command>. Examples:
           /<command> - Fakes your joining of the server
